version: '3'
services:
  json-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./data/db.json:/data/data.json
    environment:
      - JSON_SERVER_PORT=3000
