version: "3"

services:
  json-server:
    container_name: json-server-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JSON_SERVER_PORT=$JSON_SERVER_PORT
    tty: true
    volumes:
      - ./data:/data
    ports:
      - $JSON_SERVER_PORT:$JSON_SERVER_PORT